# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: pretty-format-json
        args: ['--autofix']
      - id: double-quote-string-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending

  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ['--max-line-length=120']

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8

  # - repo: https://github.com/psf/black
  #   rev: 20.8b1
  #   hooks:
  #     - id: black
  #       args: [--skip-string-normalization, --line-length=120]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.782
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [pydantic] # add if use pydantic

  - repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
      - id: isort

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.6.0
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.3.54
    hooks:
      - id: editorconfig-checker
      - id: editorconfig-checker-system