encoding: "utf-8"
timezone: "Europe/Warsaw"
lsi: true
safe: false
incremental: true

markdown: kramdown
markdown_ext: "md"
# markdown: CommonMark
# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table"]

repository: "piotr-zuralski/piotr-zuralski.github.io"
github_username: "piotr-zuralski"

social:
  name: Piotr Żuralski
  links: # jekyll-seo-tag > social aliases (sameAs)
    - https://keybase.io/piotr_zuralski/
    - https://github.com/piotr-zuralski
    - https://gitlab.com/piotr-zuralski
    - https://stackoverflow.com/users/3580681/piotr-%C5%BBuralski?tab=profile
    - https://www.linkedin.com/in/piotrzuralski/
    - https://profile.codersrank.io/user/piotr-zuralski
    - https://www.hackerrank.com/piotr_zuralski
    - https://twitter.com/piotr_zuralski
    - https://www.crunchbase.com/person/piotr-%C5%BBuralski
    - http://www.goldenline.pl/piotr-zuralski/
    - https://medium.com/@piotr.zuralski
    - https://www.slideshare.net/Piotruralski
    - https://about.me/piotr-zuralski
    - https://linktr.ee/piotr_zuralski

author: "Piotr Żuralski"
title: "Piotr Żuralski – Senior Software Engineer"
description: "Piotr Żuralski, Senior Developer, Engineer, with over 10 years experience in commercial web development"

copyright:
  year: 2007

lang: "en-GB"
locale: "en-GB"
language: "en-GB"

languages: ["en", "pl", "es", "de"]
cookie_lang: "hl"

exclude_from_localizations: ["files", "assets", "resources"]

plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

twitter:
  username: piotr_zuralski

webmaster_verifications:
  google: "x_sZsZidR01cJyzgbqip2AHTGLgAvs-8f0razmbHUpM"
  bing: "057036BF9DB13D64C6CA4552C61AC17A"
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title_separator: "-"
search: true
read_time: true
breadcrumbs: true
breadcrumb_home_label: "Home"
breadcrumb_separator: ">"

# Filtering Content
show_drafts         : false
limit_posts         : 0
future              : false
published           : false
unpublished         : true

paginate: 10

defaults:
  -
    scope:
      path:      "assets/css/*"
    values:
      sitemap:   false
      permalink: pretty
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout:    "single"
#      permalink: /:locale/:categories/:title:output_ext
      author:   "Piotr Żuralski"
      excerpt_separator: "<!--more-->"
      sidebar:
        nav: social_links

  -   scope:
        path: "./_pages/"
        type: "pages"
      values:
        layout:  "single"
        sidebar:
          nav: social_links
  # -
  #   scope:
  #     path: "_pages/"
  #     type: "pages"
  #   values:
  #     layout: "page"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"
  # -
  #   scope:
  #     path: "_pages/de"
  #     type: "pages"
  #   values:
  #     layout: "page"
  #     lang:    de-GE
  #     locale:  de
  # -
  #   scope:
  #     path: "_pages/es"
  #     type: "pages"
  #   values:
  #     layout: "page"
  #     lang:      es-ES
  #     locale:    es
  # -
  #   scope:
  #     path: "posts"
  #     type: "posts"
  #   values:
  #     layout: "post"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"
  # -
  #   scope:
  #     path: "projects"
  #     type: "pages"
  #   values:
  #     layout: "project"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"

exclude:
  - ".github/"
  - ".history/"
  - "TODO.md"
  - "README.md"
  - "Makefile"
  - ".jekyll-cache"
  - "LICENSE"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "/.tmp/"

include:
  - "_pages"

plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-time-to-read
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-paginate
