encoding: "utf-8"
timezone: Europe/London
lang: en-GB
locale: en
lsi: true
safe: false
incremental: true

markdown: kramdown
markdown_ext: "md"
# markdown: CommonMark
# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table"]

url: "https://piotr-zuralski.github.io"
repository: "piotr-zuralski/piotr-zuralski.github.io"
github_username: "piotr-zuralski"
# author: "Piotr Żuralski"
author: piotr-zuralski
excerpt_separator: "<!--more-->"

social:
  links:
    - https://keybase.io/piotr_zuralski/
    - https://github.com/piotr-zuralski
    - https://gitlab.com/piotr-zuralski
    - https://stackoverflow.com/users/3580681/piotr-%C5%BBuralski?tab=profile
    - https://www.linkedin.com/in/piotrzuralski/
    - https://profile.codersrank.io/user/piotr-zuralski
    - https://www.hackerrank.com/piotr_zuralski
    - https://twitter.com/piotr_zuralski
    - https://www.crunchbase.com/person/piotr-%C5%BBuralski
    - http://www.goldenline.pl/piotr-zuralski/
    - https://medium.com/@piotr.zuralski
    - https://www.slideshare.net/Piotruralski
    - https://about.me/piotr-zuralski
    - https://linktr.ee/piotr_zuralski
# seo:

title: "Piotr Żuralski – Senior Engineer"
description: "Senior Engineer, Developer, with over 10 years experience in commercial web development"

copyright:
  sinceYear: 2007
  currentYear: 2020

experience:
  sinceYear: 2007
  currentYear: 2020
  experience: 13

languages: ["en", "pl", "es", "de"]
exclude_from_localizations: ["files", "assets", "resources"]

plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

twitter:
  username: piotr_zuralski

webmaster_verifications:
  google: "x_sZsZidR01cJyzgbqip2AHTGLgAvs-8f0razmbHUpM"
  bing: "057036BF9DB13D64C6CA4552C61AC17A"
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

# Filtering Content
show_drafts: false
limit_posts: 0
future: false
unpublished: false

defaults:
  - scope:
      path: "assets/css/*"
    values:
      layout: null
      search: exclude
      sitemap: false
      stylesheet: true
  - scope:
      path: "assets/scss/*"
    values:
      layout: null
      search: exclude
      sitemap: false
      stylesheet: true
  - scope:
      path: "assets/js/*"
    values:
      layout: null
      search: exclude
      sitemap: false
      javascript: true
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  #   scope:
  #     path: "_pages/"
  #     type: "pages"
  #   values:
  #     layout: "page"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"
  - scope:
      path: _pages/
      type: pages
    values:
      type: pages
  - scope:
      path: _pages/de/
      type: pages
    values:
      timezone: Europe/Berlin
      lang: de-GE
      locale: de
  - scope:
      path: _pages/en/
      type: pages
    values:
      timezone: Europe/London
      lang: en-GB
      locale: en
  - scope:
      path: _pages/es/
      type: pages
    values:
      timezone: Europe/Madrid
      lang: es-ES
      locale: es
  - scope:
      path: _pages/pl/
      type: pages
    values:
      timezone: Europe/Warsaw
      lang: pl-PL
      locale: pl
  # -
  #   scope:
  #     path: "posts"
  #     type: "posts"
  #   values:
  #     layout: "post"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"
  # -
  #   scope:
  #     path: "projects"
  #     type: "pages"
  #   values:
  #     layout: "project"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"

exclude:
  - .github/
  - .history/
  - Gemfile
  - Gemfile.lock
  - TODO.md
  - README.md
  - Makefile
  - .jekyll-cache

include:
  - _pages/

plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-time-to-read
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-paginate
