encoding: "utf-8"
timezone: Europe/Warsaw
lang: en-GB
lsi: true
safe: false
incremental: true

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

author: "Piotr Żuralski"

social:
  links:
    - https://keybase.io/piotr_zuralski/
    - https://github.com/piotr-zuralski
    - https://gitlab.com/piotr-zuralski
    - https://stackoverflow.com/users/3580681/piotr-%C5%BBuralski?tab=profile
    - https://www.linkedin.com/in/piotrzuralski/
    - https://twitter.com/piotr_zuralski
    - https://www.crunchbase.com/person/piotr-%C5%BBuralski
    - http://www.goldenline.pl/piotr-zuralski/
    - https://medium.com/@piotr.zuralski
    - https://www.slideshare.net/Piotruralski
    - https://about.me/piotr-zuralski
    - https://linktr.ee/piotr_zuralski
# seo:

title: "Piotr Żuralski – Senior Software Engineer"
description: "Piotr Żuralski, Senior Developer, Engineer, with over 10 years experience in commercial web development"

languages: ["en", "pl", "es", "de"]
exclude_from_localizations: ["files", "assets", "resources"]

plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

twitter:
  username: piotr_zuralski

webmaster_verifications:
  google: x_sZsZidR01cJyzgbqip2AHTGLgAvs-8f0razmbHUpM
  bing: 057036BF9DB13D64C6CA4552C61AC17A
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

# Filtering Content
show_drafts         : false
limit_posts         : 0
future              : false
unpublished         : false

defaults:
  -
    scope:
      path:      "assets/css/*"
    values:
      sitemap:   false
      permalink: pretty
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout:    "default"
#      permalink: /:locale/:categories/:title:output_ext
      author:   "Piotr Żuralski"
      excerpt_separator: "<!--more-->"
  -
    scope:
      path: "_pages/"
      type: "pages"
    values:
      layout: "page"
      lang:      en-GB
      locale:    en
      # categories: ""
      # permalink:  "/:locale/:categories/:title:output_ext"
  -
    scope:
      path: "_pages/de"
      type: "pages"
    values:
      layout: "page"
      lang:    de-GE
      locale:  de
  -
    scope:
      path: "_pages/es"
      type: "pages"
    values:
      layout: "page"
      lang:      es-ES
      locale:    es
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      lang:      en-GB
      locale:    en
      # categories: ""
      # permalink:  "/:locale/:categories/:title:output_ext"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      lang:      en-GB
      locale:    en
      # categories: ""
      # permalink:  "/:locale/:categories/:title:output_ext"

exclude:
  - ".github/"
  - ".history/"
  - "Gemfile"
  - "Gemfile.lock"
  - "TODO.md"
  - "README.md"
  - "Makefile"
  - ".jekyll-cache"

include:
  - "_pages/"
  - "_pages/*"
  - "_pages/*/*"
  - "_pages/de/*"
  - "_pages/en/*"
  - "_pages/es/*"
  - "_pages/pl/*"

plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-time-to-read
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-paginate