encoding: "utf-8"
timezone: Europe/London
lang: en-GB
locale: en
lsi: true
safe: false
incremental: true

markdown: kramdown
markdown_ext: "md"
# markdown: CommonMark
# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table"]

title: "Piotr Żuralski – Senior Engineer"
description: "Senior Engineer, Developer, with 13+ years of experience in commercial web development"

url: https://piotr-zuralski.github.io
repository: piotr-zuralski/piotr-zuralski.github.io
github_username: piotr-zuralski

twitter:
  username: piotr_zuralski
  card: summary

excerpt_separator: "<!--more-->"

author:
  name: Piotr Żuralski
  twitter: piotr_zuralski
  github: piotr-zuralski

seo:
  name: Piotr Żuralski
  publisher:
    type: Person
    name: Piotr Żuralski
  links:
    - https://registry.jsonresume.org/piotr-zuralski
    - https://www.linkedin.com/in/piotrzuralski/
    - https://github.com/piotr-zuralski
    - https://profile.codersrank.io/user/piotr-zuralski
    - https://nofluffjobs.com/profile/piotrzuralski
    - https://stackoverflow.com/users/3580681/piotr-zuralski?tab=profile
    - https://stackoverflow.com/cv/piotr-zuralski
    - https://stackoverflow.com/story/piotr-zuralski
    - https://www.hackerrank.com/piotr_zuralski
    - https://gitconnected.com/piotr-zuralski
    - https://twitter.com/piotr_zuralski
    - https://www.crunchbase.com/person/piotr-%C5%BBuralski
    - http://www.goldenline.pl/piotr-zuralski/
    - https://medium.com/@piotr.zuralski
    - https://dev.to/piotr_zuralski
    - https://www.slideshare.net/Piotruralski
    - https://about.me/piotr-zuralski
    - https://linktr.ee/piotr_zuralski
    - https://keybase.io/piotr_zuralski/
    - https://gitlab.com/piotr-zuralski
    - https://piotr.zuralski.net/
    - https://piotr-zuralski.github.io/
    - https://reddit.com/user/piotr-zuralski

webmaster_verifications:
  google: "x_sZsZidR01cJyzgbqip2AHTGLgAvs-8f0razmbHUpM"
  bing: "057036BF9DB13D64C6CA4552C61AC17A"
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

google_analytics: UA-2579235-14

copyright:
  sinceYear: 2007
  currentYear: 2020

experience:
  sinceYear: 2008
  currentYear: 2020
  experience: 13

languages: ["en", "pl", "es", "de"]
exclude_from_localizations: ["files", "assets", "resources"]

plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# Filtering Content
show_drafts: false
limit_posts: 0
future: false
unpublished: false

defaults:
  - scope:
      path: "assets/css/*"
    values:
      layout: ""
      search: exclude
      sitemap: false
      stylesheet: true
  - scope:
      path: "assets/js/*"
    values:
      layout: ""
      search: exclude
      sitemap: false
      javascript: true
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      timezone: Europe/London
      lang: en-GB
      locale: en
  - scope:
      path: "/de/"
      type: "pages"
    values:
      layout: "default"
      timezone: Europe/Berlin
      lang: de-GE
      locale: de
  - scope:
      path: "/en/"
      type: "pages"
    values:
      layout: "default"
      timezone: Europe/London
      lang: en-GB
      locale: en
  - scope:
      path: "/es/"
      type: "pages"
    values:
      layout: "default"
      timezone: Europe/Madrid
      lang: es-ES
      locale: es
  - scope:
      path: "/pl/"
      type: "pages"
    values:
      layout: "default"
      timezone: Europe/Warsaw
      lang: pl-PL
      locale: pl
  # -
  #   scope:
  #     path: "posts"
  #     type: "posts"
  #   values:
  #     layout: "post"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"
  # -
  #   scope:
  #     path: "projects"
  #     type: "pages"
  #   values:
  #     layout: "project"
  #     lang:      en-GB
  #     locale:    en
  #     # categories: ""
  #     # permalink:  "/:locale/:categories/:title:output_ext"

exclude:
  - .github/
  - .history/
  - .jekyll-cache
  - .pre-commit-config.yaml
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - node_modules/
  - package.json
  - Pipfile
  - Pipfile.lock
  - README.md
  - TODO.md
  - vendor/
  - yarn.lock

include:
  - _pages

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    category: archive-category
    tag: archive-tag
  permalinks:
    # year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/tag/:name.html'
    category: '/category/:name/'

plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-time-to-read
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-paginate
