encoding: UTF-8
lang: en-GB
#lsi: true

author: 
  name: Piotr Żuralski
  twitter: piotr_zuralski

description: ""
title: Piotr Żuralski
#site: Piotr Żuralski

twitter:
  username: piotr_zuralski

webmaster_verifications:
  google: x_sZsZidR01cJyzgbqip2AHTGLgAvs-8f0razmbHUpM
  bing: 057036BF9DB13D64C6CA4552C61AC17A
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

defaults:
  -
    scope:
      path:      "assets/css/*"
    values:
      sitemap:   false
      permalink: pretty
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      lang:      en-GB
      locale:    en
      layout:    "default"
      permalink: /:locale/:categories/:title:output_ext
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"

exclude:
  - ".github"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

