encoding: UTF-8
author: Piotr Żuralski
description: ""
title: Piotr Żuralski
#site: Piotr Żuralski

twitter:
  username: piotr_zuralski
  
facebook:
  locale: en_UK

social:
  name: Piotr Żuralski
  links:
    - https://keybase.io/piotr_zuralski/
    - https://github.com/piotr-zuralski
    - https://gitlab.com/piotr-zuralski
    - https://stackoverflow.com/users/3580681/piotr-%C5%BBuralski?tab=profile
    - https://www.linkedin.com/in/piotrzuralski/
    - https://profile.codersrank.io/user/piotr-zuralski
    - https://twitter.com/piotr_zuralski
    - https://www.crunchbase.com/person/piotr-%C5%BBuralski
    - https://www.goldenline.pl/piotr-zuralski/
    - https://medium.com/@piotr.zuralski
    - https://www.slideshare.net/Piotruralski
    - https://about.me/piotr-zuralski
    - https://linktr.ee/piotr_zuralski
    - https://piotr.zuralski.net
    - https://zuralski.net

webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

lang: en_UK
